github icon features added
Srimathij/Indra_Bot pull request #40
Opened 2021-03-28 04:53 UTC by Varun8216889

### Pull Request

This PR fixes 

1. What type of change does your PR bring? 
    - [ ] Bug fix
    - [ ] Feature Update
    - [ ] Issue fix
    - [ ] Doc fix/update
    - [ ] Other

2. Any else you want to convey? (Additional context)

2021-03-28 09:07 UTC, alphaX86 commented
Um, you could have unchanged that work flow file

2021-03-28 09:07 UTC, alphaX86 commented
Maybe I'll open a separate issue for it. Then you can work on

2021-03-28 09:20 UTC, Varun8216889 commented
ok
 I linked the icon on the about page but there is still an error about 'All jobs have failed'

2021-03-28 15:48 UTC, alphaX86 commented
Don't need to worry on that, we're trying to figure out

2021-03-28 15:48 UTC, alphaX86 requested changes

2021-03-28 15:48 UTC, alphaX86 commented on .github/workflows/label.yml
> +  label:level0
Revert those changes alone

2021-03-28 15:49 UTC, alphaX86 commented on .github/workflows/label.yml
> +  label:level0
Bring them back

2021-03-29 01:39 UTC, alphaX86 approved these changes
LGTM 👍

2021-03-29 01:39 UTC, merged

2021-03-29 04:39 UTC, Varun8216889 commented
thank u so much for showing faith in me and for giving me a chance to contribute.
it is my first PR and I am so happy. It is all because of u.

2021-03-29 04:52 UTC, alphaX86 commented
@Varun8216889 You're welcome and keep contributing bud! You got this! 👍

2021-03-29 04:56 UTC, Varun8216889 commented
if u find some issue plz let me know. I would love to contribute