Fixed nav bar and logo and updated the website responsiveness
Srimathij/Indra_Bot pull request #41
Opened 2021-03-28 16:22 UTC by Avishake007

### Pull Request

This PR fixes  #33 

1. What type of change does your PR bring? 
    - [x] Bug fix

2021-03-28 16:51 UTC, Avishake007 commented
@alphaX86 @Srimathij  could you please tell me why its showing all checks failed and where I am doing wrong.

2021-03-29 01:35 UTC, alphaX86 commented
Don't bother the checks @Avishake007 I'm fixing that....

2021-03-29 14:16 UTC, alphaX86 requested changes

2021-03-29 14:16 UTC, alphaX86 commented on .github/workflows/label.yml
> +  label: label2
Neglect those changes. Please revert them

2021-03-29 14:17 UTC, alphaX86 commented on .github/workflows/label.yml
> +  label: label2
Do that change alone, that's enough. I didn't say you to make this change. I'm still trying to fix them

2021-03-30 16:14 UTC, alphaX86 commented
One sec.. reviewing...

2021-03-30 16:21 UTC, alphaX86 commented
@Avishake007 the responsiveness is perfect! But there's an issue now, I guess it's due to recent changes

2021-03-30 16:22 UTC, alphaX86 commented
![image](https://user-images.githubusercontent.com/59508546/113022298-151ec680-91a2-11eb-9396-378a16bde532.png)

Above the image there are actually links and icons below the profiles, it seems a bit messed up

2021-03-30 16:22 UTC, alphaX86 requested changes
Could you make those changes I suggested?

2021-03-30 16:26 UTC, alphaX86 commented
Also you may need to refine a bit.... as below....
![image](https://user-images.githubusercontent.com/59508546/113022621-6c249b80-91a2-11eb-8d22-28f2eb4b6921.png)


I'll send some PRs for ref

2021-03-30 16:27 UTC, alphaX86 commented
Refer PRs #40 #37 for idea to remake

2021-03-31 15:59 UTC, alphaX86 commented
The site now works as expected! Great work @Avishake007 👏

2021-03-31 15:59 UTC, alphaX86 approved these changes
LGTM! Good to go

2021-03-31 16:00 UTC, merged